<a href="https://colab.research.google.com/github/Raghul1694/introduction1/blob/main/cheetsheet_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import csv

In [2]:
# Find an object type
num_person = 10
print(f"Type of num_person: {type(num_person)}")

Type of num_person: <class 'int'>

In [40]:
dfs = pd.read_csv("/content/ds1.csv")
dfs.head(10)

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,Salary
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,168251
1,940761,Ms.,Brenda,S,Robinson,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,51063
2,428945,Dr.,Joe,W,Robinson,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor,50155
3,408351,Drs.,Diane,I,Evans,F,diane.evans@yahoo.com,Jason Evans,Michelle Evans,Allen,180294
4,193819,Mr.,Benjamin,R,Russell,M,benjamin.russell@charter.net,Gregory Russell,Elizabeth Russell,Nelson,117642
5,499687,Mr.,Patrick,F,Bailey,M,patrick.bailey@aol.com,Ralph Bailey,Laura Bailey,Henderson,72305
6,539712,Ms.,Nancy,T,Baker,F,nancy.baker@bp.com,Scott Baker,Judy Baker,Thomas,98189
7,380086,Mrs.,Carol,V,Murphy,F,carol.murphy@gmail.com,Eugene Murphy,Katherine Murphy,Peterson,60918
8,477616,Hon.,Frances,B,Young,F,frances.young@gmail.com,Fred Young,Lillian Young,Diaz,121587
9,162402,Hon.,Diana,T,Peterson,F,diana.peterson@hotmail.co.uk,Jonathan Peterson,Christina Peterson,Ross,43010

In [18]:
New = df[["Emp ID", "Salary"]]
New.tail(5)

    Emp ID  Salary
95  639892  129774
96  704709  156194
97  461593   95673
98  392491   51015
99  495141   93650

In [14]:
max_Salary = df["Salary"].max()
max_Salary

197537

In [36]:
p=df.groupby("Emp ID").size().to_frame("count").reset_index()
p

    Emp ID  count
0   134841      1
1   153989      1
2   158666      1
3   162402      1
4   183071      1
..     ...    ...
95  958326      1
96  969580      1
97  969964      1
98  971640      1
99  979607      1

[100 rows x 2 columns]

In [21]:
df.groupby("Salary").mean()
df.groupby("Salary").sum()
df.groupby("Salary").size()

Salary
42005     1
43010     1
43867     1
46945     1
48736     1
         ..
186200    1
186280    1
190139    1
190765    1
197537    1
Length: 100, dtype: int64

In [27]:
df4 = pd.read_csv("/content/123.csv")
df4.head(3)

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2
0,CPIQ.SE901,1914.06,13.167858,FINAL,Index,CPI,CPI Level 1 Groups for New Zealand,Food,NaN
1,CPIQ.SE901,1914.09,0.000000,FINAL,Index,CPI,CPI Level 1 Groups for New Zealand,Food,NaN
2,CPIQ.SE901,1914.12,0.000000,FINAL,Index,CPI,CPI Level 1 Groups for New Zealand,Food,NaN

In [28]:
# Convert 'Data_value' column to numeric if possible, handling errors
df4['Data_value'] = pd.to_numeric(df4['Data_value'], errors='coerce')

# Calculate the mean, ignoring non-numeric values
df4.groupby(["Period","Data_value"]).mean(numeric_only=True)
df4.groupby(["Period","Data_value"]).sum(numeric_only=True)

                    Series_title_2
Period  Data_value
1914.06 13.167858              0.0
1914.09 0.000000               0.0
1914.12 0.000000               0.0
1915.03 0.000000               0.0
1915.06 0.000000               0.0
1915.09 14.919183              0.0
1915.12 0.000000               0.0
1916.03 0.000000               0.0
1916.06 0.000000               0.0
1916.09 15.801429              0.0
1916.12 0.000000               0.0

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Series_title_2']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Series_title_2'}, axis=1)
              .sort_values('Series_title_2', ascending=True))
  xs = counted['Series_title_2']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_0.sort_values('Series_title_2', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Series_title_2')
_ = plt.ylabel('count()')

In [29]:
df[0:10]

   Emp ID  Salary
0  677509  168251
1  940761   51063
2  428945   50155
3  408351  180294
4  193819  117642
5  499687   72305
6  539712   98189
7  380086   60918
8  477616  121587
9  162402   43010

In [30]:
# drop all rows with "na" in any of the column
df.dropna()
# keep the data frame with valid entries (no "nan") in the same variable "df"
df.dropna(inplace=True)

In [31]:
# store in a new df (inplace not used)
df_new = df.dropna(axis='columns')

In [32]:
df_new = df.dropna(how='all')

In [43]:
# simple solution (new df created)
dfs_new = dfs[dfs['Gender'].notnull()]
# using dropna() (no new df created)
dfs.dropna(subset=['Gender'], how='all', inplace=True)

In [49]:
dfs = dfs.drop_duplicates(['Name Prefix','First Name','Salary'], keep='last')
for index, row in dfs.iterrows(): # Change df to dfs
   curr_authorname = row['First Name']
   curr_email = row['E Mail']

In [41]:
dfs

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,Salary
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,168251
1,940761,Ms.,Brenda,S,Robinson,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,51063
2,428945,Dr.,Joe,W,Robinson,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor,50155
3,408351,Drs.,Diane,I,Evans,F,diane.evans@yahoo.com,Jason Evans,Michelle Evans,Allen,180294
4,193819,Mr.,Benjamin,R,Russell,M,benjamin.russell@charter.net,Gregory Russell,Elizabeth Russell,Nelson,117642
...,...,...,...,...,...,...,...,...,...,...,...
95,639892,Mr.,Jose,K,Hill,M,jose.hill@hotmail.com,Carlos Hill,Anna Hill,Hayes,129774
96,704709,Dr.,Harold,Z,Nelson,M,harold.nelson@gmail.com,Richard Nelson,Pamela Nelson,Smith,156194
97,461593,Ms.,Nicole,O,Ward,F,nicole.ward@yahoo.com,Ralph Ward,Julia Ward,Lee,95673
98,392491,Mrs.,Theresa,R,Murphy,F,theresa.murphy@gmail.com,George Murphy,Jacqueline Murphy,Peterson,51015
99,495141,Drs.,Tammy,B,Young,F,tammy.young@comcast.net,Andrew Young,Brenda Young,Robinson,93650

Convert/transform list of list to data frame

In [51]:
lst_pets = [['dog', 1], ['cat', 2], ['fish', 3]]
df = pd.DataFrame(lst_pets, columns=['animal', 'amount'])
df

  animal  amount
0    dog       1
1    cat       2
2   fish       3

In [53]:
df.columns = ["new_col1", "new_col2"] # Assign a list of two column names

In [54]:
old_names = ['$a', '$b', '$c', '$d', '$e']
new_names = ['a', 'b', 'c', 'd', 'e']
df.rename(columns=dict(zip(old_names, new_names)), inplace=True)

In [57]:
# custom function
def to_minutes(row):
   # Assuming 'new_col2' contains the number of hours
   return row["new_col2"] * 60
# create new column
df['newcolumn'] = df.apply(to_minutes, axis=1)
df

  new_col1  new_col2  newcolumn
0      dog         1         60
1      cat         2        120
2     fish         3        180

In [60]:
age = 10  # Assign a value to age. You can change this to any number.
name = "dog" # Assign a value to name. You can change this to any string.

if age == 10 and name == "dog": # conditional "and"
    print("10")
elif age == 1 or age == 5: # conditional "or"
    print("either 1 or 5")
else:
    print("else")

10

In [62]:
# only those who have exact age of 18 or 20
# Assuming 'new_col1' represents age, change "age" to "new_col1"
df_18_20 = df[df["new_col1"].isin([18, 20])]

# only those rows that have pet_type either "dog" or "cat"
# Assuming 'new_col2' represents pet type, change "pet_type" to "new_col2"
df_dog_cat = df[df["new_col2"].isin(["dog", "cat"])]

In [63]:
str_message = 'Life will be truly wonderful on a wonderful planet.'
# returns index 19 (find the first occurrence starting from left side)
print(str_message.find('wonderful'))
# returns index 34 (find the first occurrence starting from right side)
print(str_message.rfind('wonderful'))
# returns index 19
print(str_message.find('wonder'))
# find index of "wonder" after index 20; returns index 34
print(str_message.find('wonder', 20))

19
34
19
34

In [64]:
import random
# generates a random number between 0 and 1
random_num = random.random()
print(random_num)

0.617339844786422

In [65]:
from random import randrange
# approach 1: randomly generate a number between 0 and 10
print(randrange(10))
print(randrange(0, 10))
# approach 2:  randomly generate a number between 0 and 10
import random
# randomly generate a number between 0 and 10 (includes 10)
print(random.randint(0, 10))

9
3
5

In [70]:
# Define the variables before using them in the f-string
name = "Raghul"
email = "123@email.com"
affiliation = "Affiliation"
coauthors_names = "author1, author2"

# construct line concatenate other variables with delimiter ,
curr_line = f"{name},{email},{affiliation},{coauthors_names}"
print(curr_line)

Raghul,123@email.com,Affiliation,author1, author2

In [74]:
dfs.where(dfs["Gender"] == "M")

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,Salary
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,428945.0,Dr.,Joe,W,Robinson,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor,50155.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,193819.0,Mr.,Benjamin,R,Russell,M,benjamin.russell@charter.net,Gregory Russell,Elizabeth Russell,Nelson,117642.0
...,...,...,...,...,...,...,...,...,...,...,...
95,639892.0,Mr.,Jose,K,Hill,M,jose.hill@hotmail.com,Carlos Hill,Anna Hill,Hayes,129774.0
96,704709.0,Dr.,Harold,Z,Nelson,M,harold.nelson@gmail.com,Richard Nelson,Pamela Nelson,Smith,156194.0
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
# source: geeksforgeeks
import pandas as pd

# Sample DataFrame (replace this with your actual data)
data = pd.DataFrame({'Team': ['Atlanta Hawks', 'Boston Celtics', 'Chicago Bulls'],
                     'Points': [100, 95, 110]})

# making boolean series for a team name
filter = data["Team"]=="Atlanta Hawks"

# filtering data
df.where(filter)

  new_col1  new_col2  newcolumn
0      dog       1.0       60.0
1      NaN       NaN        NaN
2      NaN       NaN        NaN

In [80]:
# Convert 'new_col1' to numeric type before filtering
df['new_col1'] = pd.to_numeric(df['new_col1'], errors='coerce')  # 'coerce' handles non-numeric values by setting them to NaN

# Multiple filter condition:
df[(df['new_col1'] >= 1) & (df['new_col1'] <= 1)]

Empty DataFrame
Columns: [new_col1, new_col2, newcolumn]
Index: []

In [81]:
# pick values from a specific columns
# iloc returns index
# all rows, columns 0 to 9 (exclude 9); returns numpy array
arr_num_x = df.iloc[:,0:9].values
# all rows, column 0; returns numpy array
arr_num_y = df.iloc[:,0].values

In [83]:
import traceback
# path of file
path_in_pet = "dummy.json"
try:
   f = open(path_in_pet, 'r')
except:
   traceback.print_exc()

Traceback (most recent call last):
  File "<ipython-input-83-05ca6f477e6d>", line 5, in <cell line: 4>
    f = open(path_in_pet, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'dummy.json'

In [84]:
import os

# directory name that may exist in current directory
directory = "csv_data"
# file name that may exist in current directory
file_name = "data.txt"
# returns True if dir exists
print("is dir? " + str(os.path.isdir(directory)))
# returns True if file_name exists
print("is file? " + str(os.path.isfile(file_name)))
# returns True (if dir is either file name or directory name that exists)
print("does it exist? " + str(os.path.exists(directory)))
if os.path.isfile(file_name):
   # returns the size of a file without opening it.
   print("file size: " + str(os.path.getsize(file_name)))
else:
   print("not a file to calculate size")

print("GET THREE DIFFERENT TYPE OF PATHS")
# declare file path
path_file = "/Users/lenin/Downloads/data.txt"
# return basename of path (outputs "data.txt")
print(os.path.basename(path_file))
# return directory name of a path
# output -> "/Users/lenin/Downloads"
print(os.path.dirname(path_file))
# return absolute path of a file
# output -> "/Users/lenin/Downloads/data.txt"
print(os.path.abspath(path_file))

is dir? False
is file? False
does it exist? False
not a file to calculate size
GET THREE DIFFERENT TYPE OF PATHS
data.txt
/Users/lenin/Downloads
/Users/lenin/Downloads/data.txt

In [87]:
import os

# Try to list files in the current working directory instead
current_path = os.getcwd()
lst_files = os.listdir(current_path)
print(lst_files)

['.config', '123.csv', 'ds1.csv', 'sample_data']

In [88]:
# this approach will not return output
import subprocess
subprocess.run(["ls", "-l"])

CompletedProcess(args=['ls', '-l'], returncode=0)

In [89]:
# this method will return output
import os
# run terminal command "ls -ltr"
str_list_files = os.popen("ls -ltr").read() # This will run the command and return any output
print(str_list_files)
# prints "str"
print(type(str_list_files))

total 20
drwxr-xr-x 1 root root 4096 Jul 11 13:22 sample_data
-rw-r--r-- 1 root root 9777 Jul 15 16:57 ds1.csv
-rw-r--r-- 1 root root 1013 Jul 15 17:16 123.csv

<class 'str'>

JavaScript Object Notation (JSON)

In [90]:
{
"name":"John",
"age":30,
"cars":["Ford", "BMW", "Fiat"]
}

{'name': 'John', 'age': 30, 'cars': ['Ford', 'BMW', 'Fiat']}

In [91]:
# Dict to JSON example one
import json
# dictionary data to convert as a JSON object
dict_pets = {1: 'dog', 2: 'cat',
            3: 'horse', 4: 'elephant',
            5: 'tiger'}
# prints "dict"
print(type(dict_pets))
# save as JSON object
js_data = json.dumps(dict_pets)
# prints "dict"
print(type(dict_pets))
# prints with "" for key-value (wrong json)
print(dict_pets)
# prints with "" for key-value (correct json)
print(js_data)

<class 'dict'>
<class 'dict'>
{1: 'dog', 2: 'cat', 3: 'horse', 4: 'elephant', 5: 'tiger'}
{"1": "dog", "2": "cat", "3": "horse", "4": "elephant", "5": "tiger"}

In [93]:
# Dict to JSON example two
import json

# Define the dictionary data
dict_data = {1: 'dog', 2: 'cat', 3: 'horse', 4: 'elephant', 5: 'tiger'}

# prints "dict"
with open('data.json', 'w') as outfile:
   # write "dict_data" object content to output file as JSON
   json.dump(dict_data, outfile)

In [96]:
import os
import json
# json file name with/without path
path_in_pet = "data.json"
# check if file exists
if os.path.exists(path_in_pet):
   # open in read mode
   with open(path_in_pet, 'r') as f:
       # read data
       dict_data = json.load(f)
       # prints dict
       print(type(dict_data))
       # print content
       print(dict_data)
else:
   print("file not found")

<class 'dict'>
{'1': 'dog', '2': 'cat', '3': 'horse', '4': 'elephant', '5': 'tiger'}

In [100]:
# int to string
var_age = 20
print("age is " + str(age))
# int to float
salary = 10
f_salary = float(salary)
# float to int
salary = 10.11
# convert to integer
i_salary = int(salary)

age is 10

In [101]:
from dateutil import parser
from datetime import datetime
# approach 1
dt = parser.parse("Jun 1 2021  1:11PM")
print(dt)
# approach 2
datetime_object = datetime.strptime('Jun 1 2021  1:11PM', '%b %d %Y %I:%M%p')
print(datetime_object)

2021-06-01 13:11:00
2021-06-01 13:11:00

In [102]:
# approach 1
amount = 20.123456789
f_amount = float("{:.2f}".format(amount))
print(f_amount)
# approach 2
amount = 20.123456789
f_amount =  round(amount, 2)
print(f_amount)

20.12
20.12

In [103]:
from datetime import datetime
# right now time
_now = datetime.now()
print(_now)
# format date time
_parsed = datetime.strptime(str(_now), "%Y-%m-%d %H:%M:%S.%f")
print(_now)  # prints same date time as above print
dt = datetime.strptime("21/11/06 16:30", "%d/%m/%y %H:%M")
print(dt)  # 2006-11-21 16:30:00
# get only the value of the year. assigns _year = 2006
_year = dt.year
# get only the value of the month. assigns _month = 11
_month = dt.month

2024-07-15 17:47:21.413578
2024-07-15 17:47:21.413578
2006-11-21 16:30:00

In [104]:
def to_lowercase(in_str):
   return str(in_str).lower()
# text to be converted
text = "How are you?"
# convert string to lowercase
text = to_lowercase(text)
print(text)

how are you?

In [105]:
text = "This is first line \n This is second line"
print(text)
# replace new line with blank space
text_clean = text.replace("\n", "")
print(text_clean)

This is first line
 This is second line
This is first line  This is second line

In [106]:
import re
in_str = "Hi, Where are you from?"
str_clean = re.sub(r'\W+', ' ', in_str)
# prints -> Hi Where are you from
print(str_clean)

Hi Where are you from

In [107]:
# dictionary that helps to normalise
dict_norm = {"puppyhood": "dog",
         	"puppyish": "dog",
         	"puppylike": "dog"
        	}
# dictionary that needs transformation in its value
dict_species = {"caesar": "puppyhood", "ryan": "dog", "leela": "cat"}
# create new dictionary to hold the normalised output
dict_species_norm = {}
# iterate items in dict
for key, value in dict_species.items():
	# if value exists in key of dict_norm
	if value in dict_norm.keys():
    	   dict_species_norm[key] = dict_norm[value]
	else:
    	   dict_species_norm[key] = value
# prints -> {"caesar": "dog", "ryan": "dog", "leela": "cat"}
print(dict_species_norm)

{'caesar': 'dog', 'ryan': 'dog', 'leela': 'cat'}

In [110]:
import pandas as pd
from tabulate import tabulate

def pretty_print(title, df, num_rows):
    print(title)
    print(tabulate(df.head(num_rows), headers='keys', tablefmt='psql'))
    print('\n')

# first df
df_1 = pd.DataFrame({'id': ['A01', 'A02', 'A03', 'A04'],
                   'Name': ['Dog', 'Cat', 'Eagle', 'Peacock']
                    })
pretty_print("df_1:", df_1, 10)
# second df
df_2 = pd.DataFrame({
                   'id' : ['A01', 'A06', 'A02', 'A07'],
                   'City': ['SFO', 'Chennai', 'NYC', 'Bangalore'],
                   'Age': ['12', '13', '14', '12']})
pretty_print("df_2:", df_2, 10)
# outer join => outputs all rows from both dataframes
df_new = pd.merge(df_1, df_2, on='id', how='outer')
pretty_print("merged outer:", df_new, 10)
# inner join (equi join) => outputs common intersect
df_new = pd.merge(df_1, df_2, on='id', how='inner')
pretty_print("merged inner:", df_new, 10)

# You'll need to specify the correct column names here
df_new = pd.merge(df_1, df_2, left_on='id', right_on='id', how='inner')
pretty_print("merged inner:", df_new, 10)

df_1:
+----+------+---------+
|    | id   | Name    |
|----+------+---------|
|  0 | A01  | Dog     |
|  1 | A02  | Cat     |
|  2 | A03  | Eagle   |
|  3 | A04  | Peacock |
+----+------+---------+


df_2:
+----+------+-----------+-------+
|    | id   | City      |   Age |
|----+------+-----------+-------|
|  0 | A01  | SFO       |    12 |
|  1 | A06  | Chennai   |    13 |
|  2 | A02  | NYC       |    14 |
|  3 | A07  | Bangalore |    12 |
+----+------+-----------+-------+


merged outer:
+----+------+---------+-----------+-------+
|    | id   | Name    | City      |   Age |
|----+------+---------+-----------+-------|
|  0 | A01  | Dog     | SFO       |    12 |
|  1 | A02  | Cat     | NYC       |    14 |
|  2 | A03  | Eagle   | nan       |   nan |
|  3 | A04  | Peacock | nan       |   nan |
|  4 | A06  | nan     | Chennai   |    13 |
|  5 | A07  | nan     | Bangalore |    12 |
+----+------+---------+-----------+-------+


merged inner:
+----+------+--------+--------+-------+
|    | id   | Name   | City   |   Age |
|----+------+--------+--------+-------|
|  0 | A01  | Dog    | SFO    |    12 |
|  1 | A02  | Cat    | NYC    |    14 |
+----+------+--------+--------+-------+


merged inner:
+----+------+--------+--------+-------+
|    | id   | Name   | City   |   Age |
|----+------+--------+--------+-------|
|  0 | A01  | Dog    | SFO    |    12 |
|  1 | A02  | Cat    | NYC    |    14 |
+----+------+--------+--------+-------+

In [111]:
import pandas as pd
from tabulate import tabulate
# first df
df_1 = pd.DataFrame({'id': ['A01', 'A02', 'A03', 'A04'],
                   'Name': ['Dog', 'Cat', 'Eagle', 'Peacock']
                    })
pretty_print("df_1:", df_1, 10)
# second df
df_2 = pd.DataFrame({
                   'id' : ['A01', 'A06', 'A02', 'A07'],'City': ['SFO', 'Chennai', 'NYC', 'Bangalore'],
                   'Age': ['12', '13', '14', '12']})
pretty_print("df_2:", df_2, 10)
# LEFT JOIN => takes all the values from df1, if it exists on the df2 puts it values, otherwise nan
df_new = df_1.merge(df_2, left_on=['id'], right_on = ['id'], how='left')
pretty_print("left join:", df_new, 10)
# find rows in df2 which are not in df1
df_na = df_new[df_new["City"].isna()]
pretty_print("rows in df2 which are not in df1:", df_na, 10)

df_1:
+----+------+---------+
|    | id   | Name    |
|----+------+---------|
|  0 | A01  | Dog     |
|  1 | A02  | Cat     |
|  2 | A03  | Eagle   |
|  3 | A04  | Peacock |
+----+------+---------+


df_2:
+----+------+-----------+-------+
|    | id   | City      |   Age |
|----+------+-----------+-------|
|  0 | A01  | SFO       |    12 |
|  1 | A06  | Chennai   |    13 |
|  2 | A02  | NYC       |    14 |
|  3 | A07  | Bangalore |    12 |
+----+------+-----------+-------+


left join:
+----+------+---------+--------+-------+
|    | id   | Name    | City   |   Age |
|----+------+---------+--------+-------|
|  0 | A01  | Dog     | SFO    |    12 |
|  1 | A02  | Cat     | NYC    |    14 |
|  2 | A03  | Eagle   | nan    |   nan |
|  3 | A04  | Peacock | nan    |   nan |
+----+------+---------+--------+-------+


rows in df2 which are not in df1:
+----+------+---------+--------+-------+
|    | id   | Name    |   City |   Age |
|----+------+---------+--------+-------|
|  2 | A03  | Eagle   |    nan |   nan |
|  3 | A04  | Peacock |    nan |   nan |
+----+------+---------+--------+-------+

In [116]:
# men only filter. size() gives number of rows in the data frame
# Check if 'Sex' column exists, if not, handle the error or fix the data
if 'Sex' in df.columns:
    df_state_male = df.loc[df['Sex'] == "M"]\
                     .groupby(['State'])\
                     .size()\
                     .to_frame('count')\
                     .reset_index()

    # sort by count
    df_sorted = df_state_male\
                     .sort_values(by=['count'], ascending=False)
    # gives rank as 1, 2, 3, ...
    df_sorted['rank'] = df_sorted['count'].rank(ascending=False)
    # gives percentile rank as 1, 0.9923, 0.984615, ...
    df_sorted['pct_rank'] = df_sorted['count'].rank(pct=True)
    print(df_sorted.head(10))
else:
    print("Column 'Sex' not found in the DataFrame.")
    # Investigate why the column is missing and fix the data accordingly

Column 'Sex' not found in the DataFrame.

In [115]:
from dateutil import parser
from datetime import datetime
import timeit

def fn_1():
   dt = parser.parse("Jun 1 2005  1:33PM")


def fn_2():
   datetime_object = datetime.strptime('Jun 1 2005  1:33PM', '%b %d %Y %I:%M%p')

print(timeit.timeit(stmt=fn_1, number=10**5)) # slow
print(timeit.timeit(stmt=fn_2, number=10**5)) # faster

9.771386080999946
1.051364046999879